# Pandas: Data Structure and Data Manipulation Tools

**Sources**

This notebook is a modification of chapter 7 in Python for Data Analysis, 3E.
https://wesmckinney.com/book/

All the notebooks of this book are available at:
https://github.com/wesm/pydata-book/tree/3rd-edition

**If you are a Colab user**

If you use Google Colab, uncomment the following cell to mount your Google Drive. After mounting, the notebook can read and write files in your Google Drive. Change the current directory to the folder where you saved this notebook and the data folder.

In [113]:
#from google.colab import drive
#drive.mount('/content/drive')

#%cd /content/drive/MyDrive/Colab\ Notebooks

**Import libraries and set up standards for the remainder of the notebook**

In [114]:
# import required libraries and modules, and define default setting for the notebook
# We import numpy, pandas, and matplotlib, which have been installed to our environment CIV355

import numpy as np
np.random.seed(12345)

# https://pandas.pydata.org/  Check the documentation there
import pandas as pd 
from pandas import Series, DataFrame # import modules into the local namespace if they are frequently used

import matplotlib.pyplot as plt
plt.rc("figure", figsize=(10, 6))
PREVIOUS_MAX_ROWS = pd.options.display.max_rows
pd.options.display.max_rows = 20
pd.options.display.max_columns = 20
pd.options.display.max_colwidth = 80
np.set_printoptions(precision=4, suppress=True)

# Display all outputs from each cell. Otherwise, only the last output is displayed
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

## Introduction to pandas Data Structures

https://pandas.pydata.org/  Check the documentation there

pandas will be a major tool of interest throughout much of the rest of the course. It contains data <br>
structures and data manipulation tools designed to make data cleaning and analysis fast and convenient <br>
in Python.

While pandas adopts many coding idioms from NumPy, the biggest difference is that **pandas is designed for working with <br> tabular or heterogeneous data**. NumPy, by contrast, is best suited for working with homogeneously <br>
typed numerical array data.

In this section, let's go through Series, DataFrame, and Index Objects

### Series

A Series is a one-dimensional array-like object containing a sequence of values (of similar types to NumPy types) <br>
of the same type and an associated array of data labels, called its index.

pd.Series()

In [115]:
# The Series shows the index on the left and the values on the right. 
# If the index object is not explicitly specififed, 0 to N-1 is used 
# where N is the number of elements in the Series
obj = pd.Series([4, 7, -5, 3])
print('obj:')
obj

# We can get the array representation of the Series via its array and index attributes
print('\n the values:')
obj.array
print('\n the indices:')
obj.index

obj:

0    4
1    7
2   -5
3    3
dtype: int64

 the values:

<NumpyExtensionArray>
[4, 7, -5, 3]
Length: 4, dtype: int64

 the indices:

RangeIndex(start=0, stop=4, step=1)

In [116]:
# we can create a Series with a customized index method identifying each data point with a label:
obj2 = pd.Series([4, 7, -5, 3], index=["d", "b", "a", "c"])
print('obj2:')
obj2

print('\n indices for obj2:')
obj2.index

obj2:

d    4
b    7
a   -5
c    3
dtype: int64

 indices for obj2:

Index(['d', 'b', 'a', 'c'], dtype='str')

In [117]:
# We can use labels in the index when selecting single values or a set of values

obj2["a"]

np.int64(-5)

In [118]:
obj2["d"] = 6
obj2[["c", "a", "d"]]

c    3
a   -5
d    6
dtype: int64

In [119]:
# filtering a Series with a Boolean array
print('Only display obj2 with positive entries:')
obj2[obj2 > 0]

print('\n The complete obj2:')
obj2

Only display obj2 with positive entries:

d    6
b    7
c    3
dtype: int64

 The complete obj2:

d    6
b    7
a   -5
c    3
dtype: int64

In [120]:
# scalar multiplication for Series object
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [121]:
# apply math functions to Series
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [122]:
# a Series can be seen as a fixed-length, ordered dictionary, 
# as it is a mapping of index values to data values. 
# It can be used in many contexts where you might use a dictionary

"b" in obj2

"e" in obj2

True

False

In [123]:
# If we have data contained in a Python dictionary, we can create a Series from
# it by passing the dictionary:

# sdata is a dictionary object
sdata = {"Ohio": 35000, "Texas": 71000, "Oregon": 16000, "Utah": 5000}

# obj3 is a Series 
obj3 = pd.Series(sdata)
obj3

# do you remember how you create an array by passing a list? 
# If you still remember that, you can tell the difference between ndarray and Series

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [124]:
# convert the Series back to dictionary using the method to_dict()

# When we are only passing a dictionary, the index in the resulting Series will respect
# the order of the keys according to the dictionary’s keys method, which depends on
# the key insertion order:

obj3.to_dict()

{'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [125]:
# We can override this by passing an index with the dictionary keys in the order 
# we want them to appear in the resulting Series.

# For example, we define the order as:
states = ["California", "Ohio", "Oregon", "Texas"]
# Then, we define the Series from the libraray sdata but following the defined order in states
obj4 = pd.Series(sdata, index=states)
obj4


# Here, three values found in sdata were placed in the appropriate locations, 
# but since no value for "California" was found, it appears as NaN (Not a Number), 
# which is considered in pandas to mark missing or NA values.
# Since "Utah" was not included in states, it is excluded from the resulting object

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [126]:
obj4

# The isna function in pandas is used to detect missing data
pd.isna(obj4)

# Series also has these as instance methods
obj4.isna()

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [127]:
obj4
# The notna function in pandas is used to detect non-missing (not an NA) data
pd.notna(obj4)

# Series also has these as instance methods
obj4.notna()

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [128]:
# A useful Series feature is that it automatically aligns by index 
# label in arithmetic operations
print('obj3:')
obj3
print('\n obj4:')
obj4
print('\n obj3+obj4:')
obj3 + obj4

obj3:

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

 obj4:

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

 obj3+obj4:

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [129]:
# Both the Series object itself and its index have a name attribute, 
# which integrates with other areas of pandas functionality:

# for example, we name the Series object as polulation
obj4.name = "population"
# we name the index as state
obj4.index.name = "state"

obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [130]:
obj =pd.Series([4,7,-5,3])
obj

# A Series’s index can be altered in place by assignment
obj.index = ["East", "West", "North", "South"]
obj

# After that, the default index now has been altered

0    4
1    7
2   -5
3    3
dtype: int64

East     4
West     7
North   -5
South    3
dtype: int64

### DataFrame

A DataFrame represents a rectangular table of data and contains an ordered, named collection of columns, <br>
each of which can be a different value type (numeric, string, Boolean, etc.). The DataFrame has both a row <br>
and column index; it can be thought of as a dictionary of Series all sharing the same index.

pd.DataFrame()

In [131]:
# data is defined as a dictionary
data = {"state": ["Ohio", "Ohio", "Ohio", "Nevada", "Nevada", "Nevada"],
        "year": [2000, 2001, 2002, 2001, 2002, 2003],
        "pop": [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

# covert data into DataFrame using the function DataFrame()
frame = pd.DataFrame(data)

# The resulting DataFrame will have its index assigned automatically, as with Series,
# and the columns are placed according to the order of the keys in data frame
frame

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [132]:
# the head method selects only the first five rows
frame.head()

# the tail method selects only the last five rows
frame.tail()

# how to display the last two rows? How to display the first three rows?

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

    state  year  pop
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [133]:
# If we specify a sequence of columns, the DataFrame’s columns will be arranged in that order
data

pd.DataFrame(data, columns=["year", "state", "pop"])

{'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
 'year': [2000, 2001, 2002, 2001, 2002, 2003],
 'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

   year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [134]:
# If we pass a column that isn’t contained in the dictionary, it will appear with missing
#values in the result:

frame2 = pd.DataFrame(data, columns=["year", "state", "pop", "temp"])
frame2

frame2.columns

   year   state  pop temp
0  2000    Ohio  1.5  NaN
1  2001    Ohio  1.7  NaN
2  2002    Ohio  3.6  NaN
3  2001  Nevada  2.4  NaN
4  2002  Nevada  2.9  NaN
5  2003  Nevada  3.2  NaN

Index(['year', 'state', 'pop', 'temp'], dtype='str')

In [135]:
# A column in a DataFrame can be retrieved as a Series by dictionary-like notation. 
frame2["state"]
# this method works for any column name.

# A column in a DataFrame can also be retrieved as a Series by using the .attribute notation
frame2.state
# Caution: this method works only when the column name is a valid Python variable name and does not 
# conflict with any of the method names in DataFrame. For example, if a column’s name contains
# whitespace or symbols other than underscores, it cannot be accessed with the dot attribute method.

0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
5    Nevada
Name: state, dtype: str

0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
5    Nevada
Name: state, dtype: str

In [136]:
frame2

# Rows can also be retrieved by position or name with the special iloc and loc attributes
frame2.loc[1] #label-based

frame2.iloc[1] # integer-based

   year   state  pop temp
0  2000    Ohio  1.5  NaN
1  2001    Ohio  1.7  NaN
2  2002    Ohio  3.6  NaN
3  2001  Nevada  2.4  NaN
4  2002  Nevada  2.9  NaN
5  2003  Nevada  3.2  NaN

year     2001
state    Ohio
pop       1.7
temp      NaN
Name: 1, dtype: object

year     2001
state    Ohio
pop       1.7
temp      NaN
Name: 1, dtype: object

In [137]:
# Columns can be modified by assignment

frame2["area"] = 16.5
frame2

frame2["area"] = np.arange(6.)
frame2

   year   state  pop temp  area
0  2000    Ohio  1.5  NaN  16.5
1  2001    Ohio  1.7  NaN  16.5
2  2002    Ohio  3.6  NaN  16.5
3  2001  Nevada  2.4  NaN  16.5
4  2002  Nevada  2.9  NaN  16.5
5  2003  Nevada  3.2  NaN  16.5

   year   state  pop temp  area
0  2000    Ohio  1.5  NaN   0.0
1  2001    Ohio  1.7  NaN   1.0
2  2002    Ohio  3.6  NaN   2.0
3  2001  Nevada  2.4  NaN   3.0
4  2002  Nevada  2.9  NaN   4.0
5  2003  Nevada  3.2  NaN   5.0

In [138]:
# When we assign lists or arrays to a column, the value’s length must match the length of the DataFrame. 
# If you assign a Series, its labels will be realigned exactly to the DataFrame’s index, because both Series and DataFrame are indexed objects
# missing values are inserted in any index values not present

frame2

# index of val has no overlap with the index of frame2. Therefore, elements of val are not assigned to frame2
val = pd.Series([-1.2, -1.5, -1.7], index=["two", "four", "five"])
val
frame2["area"] = val
frame2


# indices of val have partial overlap with the indices of frame2. Therefore, the assignment changes frame2
val = pd.Series([-1.2, -1.5, -1.7], index=[2, 4, 5])
val
frame2["area"] = val
frame2

   year   state  pop temp  area
0  2000    Ohio  1.5  NaN   0.0
1  2001    Ohio  1.7  NaN   1.0
2  2002    Ohio  3.6  NaN   2.0
3  2001  Nevada  2.4  NaN   3.0
4  2002  Nevada  2.9  NaN   4.0
5  2003  Nevada  3.2  NaN   5.0

two    -1.2
four   -1.5
five   -1.7
dtype: float64

   year   state  pop temp  area
0  2000    Ohio  1.5  NaN   NaN
1  2001    Ohio  1.7  NaN   NaN
2  2002    Ohio  3.6  NaN   NaN
3  2001  Nevada  2.4  NaN   NaN
4  2002  Nevada  2.9  NaN   NaN
5  2003  Nevada  3.2  NaN   NaN

2   -1.2
4   -1.5
5   -1.7
dtype: float64

   year   state  pop temp  area
0  2000    Ohio  1.5  NaN   NaN
1  2001    Ohio  1.7  NaN   NaN
2  2002    Ohio  3.6  NaN  -1.2
3  2001  Nevada  2.4  NaN   NaN
4  2002  Nevada  2.9  NaN  -1.5
5  2003  Nevada  3.2  NaN  -1.7

In [139]:
# add a new column named "eastern", which is a new column of Boolean values where the state column equals "Ohio":
frame2["eastern"] = frame2["state"] == "Ohio"
frame2

   year   state  pop temp  area  eastern
0  2000    Ohio  1.5  NaN   NaN     True
1  2001    Ohio  1.7  NaN   NaN     True
2  2002    Ohio  3.6  NaN  -1.2     True
3  2001  Nevada  2.4  NaN   NaN    False
4  2002  Nevada  2.9  NaN  -1.5    False
5  2003  Nevada  3.2  NaN  -1.7    False

In [140]:
# use the del method to delete a column
del frame2["eastern"]
frame2.columns

Index(['year', 'state', 'pop', 'temp', 'area'], dtype='str')

In [141]:
# Another common form of data is a nested dictionary of dictionaries

populations = {"Ohio": {2000: 1.5, 2001: 1.7, 2002: 3.6},
               "Nevada": {2001: 2.4, 2002: 2.9}}

# If the nested dictionary is passed to the DataFrame, pandas will interpret the outer
# dictionary keys as the columns, and the inner keys as the row indices
frame3 = pd.DataFrame(populations)
frame3

      Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     2.9

In [142]:
# We can transpose the DataFrame (swap rows and columns) with similar syntax to a NumPy array
frame3.T

        2000  2001  2002
Ohio     1.5   1.7   3.6
Nevada   NaN   2.4   2.9

In [143]:
# The keys in the inner dictionaries are combined to form the index in the result. This
# isn’t true if an explicit index is specified. 

# In this example, an explicit index is specified. The specified index does not include index value 2000.
# Therefore, the 2000 poluation at Ohio is not included in the resulting DataFrame
print('the dictionary object - populations:')
populations

pd.DataFrame(populations, index=[2001, 2002, 2003])

the dictionary object - populations:

{'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}, 'Nevada': {2001: 2.4, 2002: 2.9}}

      Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9
2003   NaN     NaN

In [144]:
# Dictionaries of Series are treated in much the same way
frame3

pdata = {"Ohio": frame3["Ohio"][:-1],
         "Nevada": frame3["Nevada"][:2]}
pd.DataFrame(pdata)

      Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     2.9

      Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4

In [145]:
# If a DataFrame’s index and columns have their name attributes set, these will also be displayed
frame3

frame3.index.name = "year"
frame3.columns.name = "state"
frame3

      Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     2.9

state  Ohio  Nevada
year
2000    1.5     NaN
2001    1.7     2.4
2002    3.6     2.9

In [146]:
# DataFrame’s to_numpy method returns the data contained in the DataFrame as a two-dimensional ndarray
frame3

frame3.to_numpy()

state  Ohio  Nevada
year
2000    1.5     NaN
2001    1.7     2.4
2002    3.6     2.9

array([[1.5, nan],
       [1.7, 2.4],
       [3.6, 2.9]])

In [147]:
# If the DataFrame’s columns are different data types, the data type of the returned
# array will be chosen to accommodate all of the columns
frame2

frame2.to_numpy()

   year   state  pop temp  area
0  2000    Ohio  1.5  NaN   NaN
1  2001    Ohio  1.7  NaN   NaN
2  2002    Ohio  3.6  NaN  -1.2
3  2001  Nevada  2.4  NaN   NaN
4  2002  Nevada  2.9  NaN  -1.5
5  2003  Nevada  3.2  NaN  -1.7

array([[2000, 'Ohio', 1.5, nan, nan],
       [2001, 'Ohio', 1.7, nan, nan],
       [2002, 'Ohio', 3.6, nan, -1.2],
       [2001, 'Nevada', 2.4, nan, nan],
       [2002, 'Nevada', 2.9, nan, -1.5],
       [2003, 'Nevada', 3.2, nan, -1.7]], dtype=object)

### Index Objects

Table 5-2. Some Index methods and properties

pd.Index()

In [148]:
# pandas’s Index objects are responsible for holding the axis labels (including a DataFrame’s column names)
# and other metadata (like the axis name or names). 
# Any array or other sequence of labels you use when constructing a Series or DataFrame is internally converted to an Index

obj = pd.Series(np.arange(3), index=["a", "b", "c"])
index = obj.index
index

index[1:]

Index(['a', 'b', 'c'], dtype='str')

Index(['b', 'c'], dtype='str')

In [149]:
# Index objects are immutable and thus can’t be modified by the user. Uncomment the following line and compile it. 
# You will see an error message. 

#index[1]='d'

In [150]:
# Immutability makes it safer to share Index objects among data structures

labels = pd.Index(np.arange(3))
labels

obj2 = pd.Series([1.5, -2.5, 0], index=labels)
print(obj2)

obj2.index is labels

Index([0, 1, 2], dtype='int64')

0    1.5
1   -2.5
2    0.0
dtype: float64

True

In [151]:
# In addition to being array-like, an Index also behaves like a fixed-size set

frame3

frame3.columns

"Ohio" in frame3.columns

2003 in frame3.index

state  Ohio  Nevada
year
2000    1.5     NaN
2001    1.7     2.4
2002    3.6     2.9

Index(['Ohio', 'Nevada'], dtype='str', name='state')

True

False

In [152]:
# Unlike Python sets, a pandas Index can contain duplicate labels

pd.Index(["foo", "foo", "bar", "bar"])

Index(['foo', 'foo', 'bar', 'bar'], dtype='str')

## Essential Functionality

### Reindexing

reindex is a method to create a new object with the values rearranged to align with the new index

Table 5-3. reindex function arguments

In [153]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=["d", "b", "a", "c"])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [154]:
# Calling reindex on this Series rearranges the data according to the new index,
# introducing missing values if any index values were not already present:

obj2 = obj.reindex(["a", "b", "c", "d", "e"])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [155]:
# For ordered data like time series, we may want to do some interpolation or filling of values when reindexing. 

obj3 = pd.Series(["blue", "purple", "yellow"], index=[0, 2, 4])
print('obj3 is:')
obj3

obj3.reindex(np.arange(6), method="ffill") # choose 'ffill' - forward filling method during reindexing

#This method helps increase the frequency of data when we have less frequent observations

obj3 is:

0      blue
2    purple
4    yellow
dtype: str

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: str

In [156]:
# With DataFrame, reindex can alter the (row) index, columns, or both. 
# When passed only a sequence, it reindexes the rows in the result

frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
                     index=["a", "c", "d"],
                     columns=["Ohio", "Texas", "California"])
frame

frame2 = frame.reindex(index=["a", "b", "c", "d"])
frame2

   Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

   Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [157]:
# The columns can be reindexed with the columns keyword
frame

states = ["Texas", "Utah", "California"]
frame.reindex(columns=states)
# Because "Ohio" was not in states, the data for that column is dropped from the result.

# Another way to reindex a particular axis is to pass the new axis labels as a positional
# argument and then specify the axis to reindex with the axis keyword
frame.reindex(states, axis="columns")

   Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

   Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

   Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [158]:
# we can also reindex by using the loc operator, and many users prefer to always do it this way.
# works only if all of the new index labels already exist in the DataFrame (whereas reindex 
# will insert missing data for new labels):
frame

frame.loc[["a", "d", "c"], ["California", "Texas"]]

   Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

   California  Texas
a           2      1
d           8      7
c           5      4

### Dropping Entries from an Axis

Dropping one or more entries from an axis is simple if we already have an index array or list without those entries, since we can use the reindex method or .loc-based indexing. <br>
The drop method will return a new object with the indicated value or values deleted from an axis:

In [159]:
#Dropping one or more entries from an axis is simple if we already have an index array or list 

obj = pd.Series(np.arange(5.), index=["a", "b", "c", "d", "e"])
print('obj:')
obj

# drop the row indexed as 'c', if any
new_obj = obj.drop("c")

print('\n After dropping the row indexed as c:')
new_obj

# drop the rows indexed as 'c' or 'd', if any
print('\n After dropping rows indexed as c or d:')
obj.drop(["d", "c"])

obj:

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

 After dropping the row indexed as c:

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

 After dropping rows indexed as c or d:

a    0.0
b    1.0
e    4.0
dtype: float64

In [160]:
# With DataFrame, index values can be deleted from either axis. 

# To illustrate this, we first create an example DataFrame:  
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=["Ohio", "Colorado", "Utah", "New York"],
                    columns=["one", "two", "three", "four"])
data

# Calling drop with a sequence of labels will drop values from the row labels (axis 0):
data.drop(index=["Colorado", "Ohio"])

#  Use the columns keyword to drop labels from the columns
data.drop(columns=["two"])


# we can also drop values from columns or rows by passing the axis value or axis name:
data.drop(["Colorado", "Ohio"], axis=0) 
#data.drop(["Colorado", "Ohio"], axis="rows") 

data.drop("two", axis=1)
#data.drop("two", axis="columns")

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

          one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

          one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

          one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

          one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [161]:
# we can also drop values from the columns by passing axis="columns":

data.drop(["two", "four"], axis="columns")

          one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

### Indexing, Selection, and Filtering

Table 5-4. Indexing options with DataFrame

Series indexing (obj[...]) works analogously to NumPy array indexing, except we can use the Series’s index values<br>
instead of only integers. Here are some examples of this:

In [162]:
# Define a Series object - obj
obj = pd.Series(np.arange(4.), index=["a", "b", "c", "d"])
obj

#Use the index value to access the corresponding value stored in Series
obj["b"]
#You will see warning messages if you use integer(s) to  
#obj[1] 
#obj[[1, 3]]

obj[["b", "a", "d"]]

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

np.float64(1.0)

b    1.0
a    0.0
d    3.0
dtype: float64

In [163]:
obj
# we can get a slice of the Series object by specifying the starting and ending indices:
obj[2:4]

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

c    2.0
d    3.0
dtype: float64

In [164]:
obj
# we can select a portion of the Series object by specifying the selection condition:
obj[obj < 2]

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

a    0.0
b    1.0
dtype: float64

In [165]:
# While we can select data by label, the preferred way to select index values is with the special loc operator

obj.loc[["b", "a", "d"]]

b    1.0
a    0.0
d    3.0
dtype: float64

In [166]:
# The reason to prefer loc is because of the different treatment of integers when indexing with []. 
# Regular []-based indexing will treat integers as labels if the index contains integers, so the behavior 
# differs depending on the data type of the index.

# The index contains integers, therefore, regular []-based indexing will treat integers as labels
obj1 = pd.Series([1, 2, 3], index=[2, 0, 1])
obj1
obj1[[0, 1, 2]]

2    1
0    2
1    3
dtype: int64

0    2
1    3
2    1
dtype: int64

In [167]:
obj2 = pd.Series([1, 2, 3], index=["a", "b", "c"])
obj2

# When using loc, the expression obj.loc[[0, 1]] will fail when the index does not contain integers
#obj2.loc[[0, 1]]

a    1
b    2
c    3
dtype: int64

In [168]:
# Since loc operator indexes exclusively with labels, there is also an iloc operator
# that indexes exclusively with integers to work consistently whether or not the index
# contains integers
obj1

obj1.iloc[[0, 1, 2]]

2    1
0    2
1    3
dtype: int64

2    1
0    2
1    3
dtype: int64

In [169]:
obj2

obj2.iloc[[0, 1, 2]]

a    1
b    2
c    3
dtype: int64

a    1
b    2
c    3
dtype: int64

In [170]:
# We can also slice with labels, but it works differently from normal Python slicing 
# in that the endpoint is inclusive
obj2

obj2.loc["b":"c"]

a    1
b    2
c    3
dtype: int64

b    2
c    3
dtype: int64

In [171]:
# Assigning values using these methods modifies the corresponding section of the Series:
obj2

obj2.loc["b":"c"] = 5
obj2

a    1
b    2
c    3
dtype: int64

a    1
b    5
c    5
dtype: int64

In [172]:
# Indexing into a DataFrame retrieves one or more columns either with a single value or sequence:

data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=["Ohio", "Colorado", "Utah", "New York"],
                    columns=["one", "two", "three", "four"])
data

# select a column
data["two"]

# select two columns in the defined order
data[["three", "one"]]

# slicing
data[:2]

# selecting data with boolean array
data[data["three"] > 5]

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

          three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

          one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [173]:
data

#produce a boolean DataFrame with a scalar comparison
data < 5

# assigning values to locations where values are less than 5
data[data < 5] = 0
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

            one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

          one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

Like Series, DataFrame has special attributes **loc** and **iloc** for label-based and
integer-based indexing, respectively. Since DataFrame is two-dimensional, you can
select a subset of the rows and columns with NumPy-like notation using either axis
labels (loc) or integers (iloc).

In [174]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=["Ohio", "Colorado", "Utah", "New York"],
                    columns=["one", "two", "three", "four"])
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [175]:
# locate the row labeled as "Colorado"
data.loc["Colorado"]

#The result of selecting a single row is a Series with an index that contains the DataFrame’s column labels.

one      4
two      5
three    6
four     7
Name: Colorado, dtype: int64

In [176]:
#To select multiple roles, creating a new DataFrame, pass a sequence of labels

data.loc[["Colorado", "New York"]]

          one  two  three  four
Colorado    4    5      6     7
New York   12   13     14    15

In [177]:
# we can combine both row and column selection in loc by separating the selections with a comma

data.loc["Colorado", ["two", "three"]]

two      5
three    6
Name: Colorado, dtype: int64

In [178]:
data

# using iloc similarly
data.iloc[2]

data.iloc[[2, 1]]

data.iloc[2, [3, 0, 1]]

data.iloc[[1, 2], [3, 0, 1]]

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

one       8
two       9
three    10
four     11
Name: Utah, dtype: int64

          one  two  three  four
Utah        8    9     10    11
Colorado    4    5      6     7

four    11
one      8
two      9
Name: Utah, dtype: int64

          four  one  two
Colorado     7    4    5
Utah        11    8    9

In [179]:
# Both loc and iloc indexing functions work with slices in addition to single labels or lists of labels
data

data.loc[:"Utah", "two"]

data.iloc[:, :3][data.three > 5]

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

Ohio        1
Colorado    5
Utah        9
Name: two, dtype: int64

          one  two  three
Colorado    4    5      6
Utah        8    9     10
New York   12   13     14

In [180]:
# Boolean arrays can be used with loc but not iloc. This is because iloc use integers

data.loc[data.three > 2]

          one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [181]:
# Working with pandas objects indexed by integers can be a stumbling block for new
# users since they work differently from built-in Python data structures like lists and
# tuples. 

ser = pd.Series(np.arange(3.))
ser

#For example, you might expect the following code to generate an error
#ser[-1]

# If you have an axis index containing integers, data selection will always be label
# oriented.If we use loc (for labels) or iloc (for integers), we will get
# exactly what you want:
ser.iloc[-1]

# slicing with integers is always integer oriented
ser[:2]

0    0.0
1    1.0
2    2.0
dtype: float64

np.float64(2.0)

0    0.0
1    1.0
dtype: float64

In [182]:
data.loc[:, "one"] = 1
data

          one  two  three  four
Ohio        1    1      2     3
Colorado    1    5      6     7
Utah        1    9     10    11
New York    1   13     14    15

In [183]:
data.iloc[2] = 5
data

          one  two  three  four
Ohio        1    1      2     3
Colorado    1    5      6     7
Utah        5    5      5     5
New York    1   13     14    15

### Arithmetic and Data Alignment

pandas can make it much simpler to work with objects that have different indexes.

Table 5-5. Flexible arithmetic methods

In [184]:
# For example, when we add objects, if any index pairs are not the same, the respective
# index in the result will be the union of the index pairs

s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=["a", "c", "d", "e"])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1],
               index=["a", "c", "e", "f", "g"])
print('s1:')
s1

print('s2:')
s2

print('s1+s2:')
s1+s2

s1:

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

s2:

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

s1+s2:

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [185]:
# In the case of DataFrame, alignment is performed on both rows and columns

df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list("bcd"),
                   index=["Ohio", "Texas", "Colorado"])
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list("bde"),
                   index=["Utah", "Ohio", "Texas", "Oregon"])
print('df1:')
df1

print('df2:')
df2

print('df1+df2:')
df1+df2

df1:

            b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

df2:

          b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

df1+df2:

            b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [186]:
df1 = pd.DataFrame({"A": [1, 2]})
df2 = pd.DataFrame({"B": [3, 4]})

print('df1:')
df1

print('df2:')
df2

print('df1+df2:')
df1+df2

df1:

   A
0  1
1  2

df2:

   B
0  3
1  4

df1+df2:

    A   B
0 NaN NaN
1 NaN NaN

#### Arithmetic methods with fill values

This is an advanced topic that can be skipped temporarily

In [187]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)),
                   columns=list("abcd"))
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)),
                   columns=list("abcde"))
df2.loc[1, "b"] = np.nan

print('df1:')
df1

print('df2:')
df2

print('df1+df2:')
df1+df2

# Using the add method on df1, we pass df2 and an argument to fill_value, which
# substitutes the passed value for any missing values in the operation
print("df1+df2:(with filled 0's)")
df1.add(df2, fill_value=0)

df1:

     a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

df2:

      a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

df1+df2:

      a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

df1+df2:(with filled 0's)

      a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [188]:
# See Table 5-5 for a listing of Series and DataFrame methods for arithmetic. 
# Each has # a counterpart, starting with the letter r, that has arguments reversed. 
# So these two statements are equivalent:

1 / df1

df1.rdiv(1)

       a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

       a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [189]:
# when reindexing a Series or DataFrame, you can also specify a different fill value
print(df1,'\n')
print(df2,'\n')

df1.reindex(columns=df2.columns, fill_value=0)

     a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

      a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

     a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

#### Operations between DataFrame and Series

As with NumPy arrays of different dimensions, arithmetic between DataFrame and
Series is also defined.

In [190]:
# When we subtract arr[0] from arr, the subtraction is performed once for each row.
# This is referred to as broadcasting

arr = np.arange(12.).reshape((3, 4))
arr

print('\narr[0]:')
arr[0]

print('\narr-arr[0]:')
arr - arr[0]

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

arr[0]:

array([0., 1., 2., 3.])

arr-arr[0]:

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [191]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),
                     columns=list("bde"),
                     index=["Utah", "Ohio", "Texas", "Oregon"])
print('frame:')
frame

series = frame.iloc[0]
print('\nseries:')
series

print('\nframe-series:')
frame-series

frame:

          b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

series:

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

frame-series:

          b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [192]:
series2 = pd.Series(np.arange(3), index=["b", "e", "f"])
print('series2:')
series2

print('\n frame:')
frame

print('\n frame+series2:')
frame + series2

series2:

b    0
e    1
f    2
dtype: int64

 frame:

          b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

 frame+series2:

          b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [193]:
# If you want to broadcast over the columns, matching on the rows, we have to
#use one of the arithmetic methods and specify to match over the index.

series3 = frame["d"]
print('series3:')
series3

print('\n frame:')
frame

print('\n substract series3 from each column of frame:')
frame.sub(series3, axis="index")

series3:

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

 frame:

          b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

 substract series3 from each column of frame:

          b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

### Function Application and Mapping

NumPy ufuncs (element-wise array methods) also work with pandas objects

In [194]:
frame = pd.DataFrame(np.random.standard_normal((4, 3)),
                     columns=list("bde"),
                     index=["Utah", "Ohio", "Texas", "Oregon"])
print('frame:')
frame

print('\n abs(frame):')
np.abs(frame)

frame:

               b         d         e
Utah   -0.204708  0.478943 -0.519439
Ohio   -0.555730  1.965781  1.393406
Texas   0.092908  0.281746  0.769023
Oregon  1.246435  1.007189 -1.296221

 abs(frame):

               b         d         e
Utah    0.204708  0.478943  0.519439
Ohio    0.555730  1.965781  1.393406
Texas   0.092908  0.281746  0.769023
Oregon  1.246435  1.007189  1.296221

In [195]:
# Another frequent operation is applying a function on one-dimensional arrays to each
#column or row. DataFrame’s apply method does exactly this:

print('frame:')
frame

# In this example, the function f, which computes the difference between the maximum and
# minimum of a Series, is invoked once on each column in frame. The result is a Series
# having the columns of frame as its index
print('\n range along rows:')
def f1(x):
    return x.max() - x.min()
frame.apply(f1)

# If we pass axis="columns" to apply, the function will be invoked once per row instead.
print('\n range along columns:')
frame.apply(f1, axis="columns")

frame:

               b         d         e
Utah   -0.204708  0.478943 -0.519439
Ohio   -0.555730  1.965781  1.393406
Texas   0.092908  0.281746  0.769023
Oregon  1.246435  1.007189 -1.296221

 range along rows:

b    1.802165
d    1.684034
e    2.689627
dtype: float64

 range along columns:

Utah      0.998382
Ohio      2.521511
Texas     0.676115
Oregon    2.542656
dtype: float64

In [196]:
# The function passed to apply need not return a scalar value; it can also return a Series with multiple values

def f2(x):
    return pd.Series([x.min(), x.max()], index=["min", "max"])
frame.apply(f2)

            b         d         e
min -0.555730  0.281746 -1.296221
max  1.246435  1.965781  1.393406

In [197]:
# Element-wise Python functions can be used, too. Suppose you wanted to compute a formatted string from 
# each floating-point value in frame. You can do this with the map method:
# The reason for the name map is that Series has a map method for applying an element-wise function
print('frame:')
frame


print('after formatting:')

def my_format(x):
    return f"{x:.2f}"

frame.map(my_format)

frame:

               b         d         e
Utah   -0.204708  0.478943 -0.519439
Ohio   -0.555730  1.965781  1.393406
Texas   0.092908  0.281746  0.769023
Oregon  1.246435  1.007189 -1.296221

after formatting:

            b     d      e
Utah    -0.20  0.48  -0.52
Ohio    -0.56  1.97   1.39
Texas    0.09  0.28   0.77
Oregon   1.25  1.01  -1.30

In [198]:
frame["e"].map(my_format)

Utah      -0.52
Ohio       1.39
Texas      0.77
Oregon    -1.30
Name: e, dtype: str

### Sorting and Ranking

#### Sorting

.sort_values() and .sort_index() method

In [199]:
# to sort lexicographically by row or column label, use the sort_index method, which returns a new, sorted object

obj = pd.Series(np.arange(4), index=["d", "a", "b", "c"])
print('obj:')
obj

print('\n after sorted by labels:')
obj.sort_index()

obj:

d    0
a    1
b    2
c    3
dtype: int64

 after sorted by labels:

a    1
b    2
c    3
d    0
dtype: int64

In [200]:
# when sorting a DataFrame, we can sort by index or columns

frame = pd.DataFrame(np.arange(8).reshape((2, 4)),
                     index=["three", "one"],
                     columns=["d", "a", "b", "c"])
print('frame:')
frame

# sort by index
print('\n after sorted by index label:')
frame.sort_index()

# sort along column
print('\n after sorted by column label:')
frame.sort_index(axis="columns")

frame:

       d  a  b  c
three  0  1  2  3
one    4  5  6  7

 after sorted by index label:

       d  a  b  c
one    4  5  6  7
three  0  1  2  3

 after sorted by column label:

       a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [201]:
# The data is sorted in ascending order by default, but can be sorted in descending order too:

print('frame:')
frame

# sort by columns
print('\n after sorted by column labels in the decreasing order:')
frame.sort_index(axis="columns", ascending=False)

frame:

       d  a  b  c
three  0  1  2  3
one    4  5  6  7

 after sorted by column labels in the decreasing order:

       d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [202]:
# The sort_values method sort a Series by its values:

obj = pd.Series([4, 7, -3, 2])

print('obj:')
obj

print('\n after sorted by values in the ascending order:')
obj.sort_values()

obj:

0    4
1    7
2   -3
3    2
dtype: int64

 after sorted by values in the ascending order:

2   -3
3    2
0    4
1    7
dtype: int64

In [203]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])
print('obj:')
obj

# Any missing values are sorted to the end of the Series by default
print('\n after sorted by values in the ascending order:')
obj.sort_values()

# Missing values can be sorted to the start instead by using the na_position option
print('\n after sorted by values in the ascending order:')
obj.sort_values(na_position="first")

obj:

0    4.0
1    NaN
2    7.0
3    NaN
4   -3.0
5    2.0
dtype: float64

 after sorted by values in the ascending order:

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

 after sorted by values in the ascending order:

1    NaN
3    NaN
4   -3.0
5    2.0
0    4.0
2    7.0
dtype: float64

In [204]:
# When sorting a DataFrame, you can use the data in one or more columns as the sort keys. 
# To do so, pass one or more column names to sort_values

frame = pd.DataFrame({"b": [4, 7, -3, 2], "a": [0, 1, 0, 1]})
print('frame:')
frame

# In this example, we sort rows by the value of column b
print('\n sorted according to column b:')
frame.sort_values("b")

# In this example, we sort rows by the values of a, and then by the values of b
print('\n sorted according to column a and then b:')
frame.sort_values(["a", "b"])

frame:

   b  a
0  4  0
1  7  1
2 -3  0
3  2  1

 sorted according to column b:

   b  a
2 -3  0
3  2  1
0  4  0
1  7  1

 sorted according to column a and then b:

   b  a
2 -3  0
0  4  0
3  2  1
1  7  1

#### Ranking

Table 5-6. Tie-breaking methods with rank

Ranking assigns ranks from one through the number of valid data points in an array,starting from the lowest value. <br>
The rank methods for Series and DataFrame are the place to look; by default, rank breaks ties by assigning each group the mean rank

In [205]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])
print('obj:')
obj

# the sorted obj is [-5, 0, 2, 4, 4, 7, 7]. 
# Therefore, -5's rank is 1, 
# 0' rank is 2, 
# 2' rank is 3, 
# two 4's rank is (4+5)/2=4.5, and 
# two 7's rank is (6+7)/2=6.5
print('\n ranks in obj in a descending order:')
obj.rank()

# rank in descending order
print('\n ranks in obj in a ascending order:')
obj.rank(ascending=False)

obj:

0    7
1   -5
2    7
3    4
4    2
5    0
6    4
dtype: int64

 ranks in obj in a descending order:

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

 ranks in obj in a ascending order:

0    1.5
1    7.0
2    1.5
3    3.5
4    5.0
5    6.0
6    3.5
dtype: float64

In [206]:
# Ranks can also be assigned according to the order in which they’re observed in the data:

# the sorted obj is [-5, 0, 2, 4, 4, 7, 7]. 
# Therefore, -5's rank is 1, 
# 0' rank is 2, 
# 2' rank is 3, 
# the first 4's rank is 4 and the second 4's rank is 5, and 
# the first 7's rank is 6 and the second 7th rank is 7
obj.rank(method="first")

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [207]:
# DataFrame can compute ranks over the rows or the columns

frame = pd.DataFrame({"b": [4.3, 7, -3, 2], "a": [0, 1, 0, 1],
                      "c": [-2, 5, 8, -2.5]})
print('frame:')
frame

# rank over columns
print('rank over columns:')
frame.rank(axis="columns")

# rank over rows
print('rank over rows:')
frame.rank(axis="rows")

frame:

     b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

rank over columns:

     b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

rank over rows:

     b    a    c
0  3.0  1.5  2.0
1  4.0  3.5  3.0
2  1.0  1.5  4.0
3  2.0  3.5  1.0

### Axis Indexes with Duplicate Labels

Series and DataFrame can use duplicate labels.

In [208]:
obj = pd.Series(np.arange(5), index=["a", "a", "b", "b", "c"])
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [209]:
# use the index.is_unique method to find out if the index has duplicated labels
obj.index.is_unique

False

In [210]:
# Data selection is one of the main things that behaves differently with duplicates.
# Indexing a label with multiple entries returns a Series, while single entries return a
# scalar value:

print('obj:')
obj

# return a Series whose labels are "a"
print('\n return those labeled with a:')
obj["a"]

# return a scalar value whose label is "c"
print('\n return those labeled with c:')
obj["c"]

obj:

a    0
a    1
b    2
b    3
c    4
dtype: int64

 return those labeled with a:

a    0
a    1
dtype: int64

 return those labeled with c:

np.int64(4)

In [211]:
# The same logic extends to indexing rows (or columns) in a DataFrame

df = pd.DataFrame(np.random.standard_normal((5, 3)),
                  index=["a", "a", "b", "b", "c"])

print('df')
df

print('\n rows indexed as b:')
df.loc["b"]

print('\n rows indexed as c:')
df.loc["c"]

df

          0         1         2
a  0.274992  0.228913  1.352917
a  0.886429 -2.001637 -0.371843
b  1.669025 -0.438570 -0.539741
b  0.476985  3.248944 -1.021228
c -0.577087  0.124121  0.302614

 rows indexed as b:

          0         1         2
b  1.669025 -0.438570 -0.539741
b  0.476985  3.248944 -1.021228

 rows indexed as c:

0   -0.577087
1    0.124121
2    0.302614
Name: c, dtype: float64

## Summarizing and Computing Descriptive Statistics

pandas objects are equipped with a set of common mathematical and statistical methods.
Most of these fall into the category of reductions or summary statistics, methods
that extract a single value (like the sum or mean) from a Series, or a Series of values
from the rows or columns of a DataFrame. Compared with the similar methods
found on NumPy arrays, they have built-in handling for missing data.

Table 5-7 is a list of common options for each reduction method

Table 5-8 is a full list of summary statistics and related methods

In [212]:
# a dataframe with missing data

df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],
                   [np.nan, np.nan], [0.75, -1.3]],
                  index=["a", "b", "c", "d"],
                  columns=["one", "two"])
print('df:')
df

# Calling DataFrame’s sum method returns a Series containing column sums
print('sum across rows:')
df.sum()

# Passing axis="columns" or axis=1 sums across the columns instead:
print('\n sum across columns:')
df.sum(axis="columns")

# using the argment skipna, we can disable the dafault method of handling missing values:
df.sum(axis="rows", skipna=False)
df.sum(axis="columns", skipna=False)

# Some aggregations, like mean, require at least one non-NA value to yield a value result
# in this example, row 'c' is all NaN. Therefore, the mean cannot be calcualted, yielding a result of NaN
print('\n mean across columns:')
df.mean(axis="columns")

# idxmin and idxmax, return indirect statistics, 
# like the index value where the minimum or maximum values are attained
print('\n maximum values of each columns are attained at:')
df.idxmax()

# Some methods are cumulative, like sumsum
print('\n cumulative sum along arows:')
df.cumsum()
print('\n cumulative sum along columns:')
df.cumsum(axis=1)

# Some methods are neither reductions nor accumulations. 
# describe is one such example, producing multiple summary statistics in one shot:
df.describe()

df:

    one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

sum across rows:

one    9.25
two   -5.80
dtype: float64

 sum across columns:

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

one   NaN
two   NaN
dtype: float64

a     NaN
b    2.60
c     NaN
d   -0.55
dtype: float64

 mean across columns:

a    1.400
b    1.300
c      NaN
d   -0.275
dtype: float64

 maximum values of each columns are attained at:

one    b
two    d
dtype: str

 cumulative sum along arows:

    one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

 cumulative sum along columns:

    one   two
a  1.40   NaN
b  7.10  2.60
c   NaN   NaN
d  0.75 -0.55

            one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [213]:
# On nonnumeric data, describe produces alternative summary statistics
obj = pd.Series(["a", "a", "b", "c"] * 4)
print('obj:')
obj

obj.describe()

obj:

0     a
1     a
2     b
3     c
4     a
5     a
6     b
7     c
8     a
9     a
10    b
11    c
12    a
13    a
14    b
15    c
dtype: str

count     16
unique     3
top        a
freq       8
dtype: object

### Correlation and Covariance

correlation: .corr() and .corrwith() methods <br>
covariance: .cov() method

In [214]:
# price = pd.read_pickle("Data/yahoo_price.pkl")
price = pd.read_csv(
    "data/yahoo_price.csv",
    index_col=0,
    parse_dates=True
)

print('price:')
price

print('rate of return:')
returns = price.pct_change() # call pct_change method to attain return (rate)
returns.tail() # display the result of the last five

price:

                  AAPL        GOOG         IBM       MSFT
Date
2010-01-04   27.990226  313.062468  113.304536  25.884104
2010-01-05   28.038618  311.683844  111.935822  25.892466
2010-01-06   27.592626  303.826685  111.208683  25.733566
2010-01-07   27.541619  296.753749  110.823732  25.465944
2010-01-08   27.724725  300.709808  111.935822  25.641571
...                ...         ...         ...        ...
2016-10-17  117.550003  779.960022  154.770004  57.220001
2016-10-18  117.470001  795.260010  150.720001  57.660000
2016-10-19  117.120003  801.500000  151.259995  57.529999
2016-10-20  117.059998  796.969971  151.520004  57.250000
2016-10-21  116.599998  799.369995  149.630005  59.660000

[1714 rows x 4 columns]

rate of return:

                AAPL      GOOG       IBM      MSFT
Date
2016-10-17 -0.000680  0.001837  0.002072 -0.003483
2016-10-18 -0.000681  0.019616 -0.026168  0.007690
2016-10-19 -0.002979  0.007846  0.003583 -0.002255
2016-10-20 -0.000512 -0.005652  0.001719 -0.004867
2016-10-21 -0.003930  0.003011 -0.012474  0.042096

In [215]:
# correlation between MSTF's return and IBM's return
returns["MSFT"].corr(returns["IBM"])

np.float64(0.4997636114415119)

In [216]:
# corvariance between MSTF's return and IBM's return

returns["MSFT"].cov(returns["IBM"])

np.float64(8.870655479703553e-05)

In [217]:
# DataFrame’s corr can return a full correlation matrix as a DataFrame
returns.corr()

          AAPL      GOOG       IBM      MSFT
AAPL  1.000000  0.407919  0.386817  0.389695
GOOG  0.407919  1.000000  0.405099  0.465919
IBM   0.386817  0.405099  1.000000  0.499764
MSFT  0.389695  0.465919  0.499764  1.000000

In [218]:
# DataFrame’s cov can return a full covariance matrix as a DataFrame
returns.cov()

          AAPL      GOOG       IBM      MSFT
AAPL  0.000277  0.000107  0.000078  0.000095
GOOG  0.000107  0.000251  0.000078  0.000108
IBM   0.000078  0.000078  0.000146  0.000089
MSFT  0.000095  0.000108  0.000089  0.000215

In [219]:
# Using DataFrame’s corrwith method, you can compute pair-wise correlations 
# between a DataFrame’s columns or rows with another Series or DataFrame

returns.corrwith(returns["IBM"])

AAPL    0.386817
GOOG    0.405099
IBM     1.000000
MSFT    0.499764
dtype: float64

In [220]:
# Passing a DataFrame computes the correlations of matching column names
# this example calculate the correlation between a company's stock raturn and its stock volume

# volume = pd.read_pickle("Data/yahoo_volume.pkl")

volume = pd.read_csv(
    "data/yahoo_volume.csv",
    index_col=0,
    parse_dates=True
)

returns.corrwith(volume)

AAPL   -0.075565
GOOG   -0.007067
IBM    -0.204849
MSFT   -0.092950
dtype: float64

### Unique Values, Value Counts, and Membership

Table 5-9 Unique, value counts, and set membership methods

In [221]:
obj = pd.Series(["c", "a", "d", "a", "c", "b", "b", "c", "c"])
print('ojb:')
obj

# The unique method gives an array of unique values in a Series
uniques = obj.unique()
print('\n unique values are:')
uniques

# The value_count method computes a Series containing value frequencies:
print('\n frequency distribution:')
obj.value_counts()

# isin performs a vectorized set membership check and can be useful in filtering a
#dataset down to a subset of values in a Series or column in a DataFrame
mask = obj.isin(["b", "c"])
print('\n extract elements that belong to the set {"b","c"}:')
obj[mask]

ojb:

0    c
1    a
2    d
3    a
4    c
5    b
6    b
7    c
8    c
dtype: str

 unique values are:

<StringArray>
['c', 'a', 'd', 'b']
Length: 4, dtype: str

 frequency distribution:

c    4
a    2
b    2
d    1
Name: count, dtype: int64

 extract elements that belong to the set {"b","c"}:

0    c
4    c
5    b
6    b
7    c
8    c
dtype: str

In [222]:
# Index.get_indexer method, which gives you an index array from an array of possibly 
# nondistinct values into another array of distinct values

to_match = pd.Series(["c", "a", "b", "b", "c", "a"])
unique_vals = pd.Series(["c", "b", "a"])
indices = pd.Index(unique_vals).get_indexer(to_match)
indices

array([0, 2, 1, 1, 0, 2])

In [223]:
data = pd.DataFrame({"Qu1": [1, 3, 4, 3, 4],
                     "Qu2": [2, 3, 1, 2, 3],
                     "Qu3": [1, 5, 2, 4, 4]})
print('data:')
data

# compute the frequency for a single column:
print('\n frequency distribution of column Qu1:')
data["Qu1"].value_counts().sort_index()

data:

   Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

 frequency distribution of column Qu1:

Qu1
1    1
3    2
4    2
Name: count, dtype: int64

In [224]:
# There is also a DataFrame.value_counts method, but it computes counts considering
# each row of the DataFrame as a tuple to determine the number of occurrences of each
# distinct row

data = pd.DataFrame({"a": [1, 1, 1, 2, 2], "b": [0, 0, 1, 0, 0]})
print('data:')
data

print('frequency distribution across rows:')
data.value_counts()

data:

   a  b
0  1  0
1  1  0
2  1  1
3  2  0
4  2  0

frequency distribution across rows:

a  b
1  0    2
2  0    2
1  1    1
Name: count, dtype: int64